### ISSUE TITLE
Hauptteil - Geschichte

### ISSUE THREAD

**Issue by Raisybear** [robinsacher/ila3-onboarding#6]

**Comment by robinsacher** [comment]
@Raisybear Why is there no description for this issue?

**Comment by Raisybear** [comment]
@robinsacher @robinsacher @robinsacher @robinsacher @robinsacher @robinsacher @robinsacher I am under the water
![grafik](https://github.com/user-attachments/assets/ba6028d8-9ac0-49f9-94c4-0c16b4172e5b)
